#include<iostream>
using namespace std;







          std::cout<<"  `/yyo-                                                                                                                  .odmy:        -+o+-`                                                                                                                       hMN         oMM-      ///`/.+ o:/+``:/  ::``:-`+`+--:-:.                   .+hds-                                                          .+ss/."<<endl;                                                                        
          std::cout<<"   `/yyo-                                                                                                                  .odmy-        -+o+-                                                                                                                      hMN         oMM-      `  ..`` ../+.`-.   .-.`` `-``-...`                 .+hdy:                                                          .+ss/.    "<<endl;                                                                        
          std::cout<<"    `/yyo-                                                                                                                  .odmy-        -+o+-                                                                                                                    hMN         oMM-        -:-`:`  /::-`. ``` ````` `. ``                 `+hdy:                                                          .+ss+.       "<<endl;                                                                       
          std::cout<<"      `+yyo-                                                                                                                  .odmy-        -+o+-                                                                                                                  hMN         oMM-        `:/.+`  +/:-/+-o-+-+..o.`/+:+:`              `+hdy:                                                          .+ss+.         "<<endl;                                                                       
          std::cout<<"        `/yyo-                                                                                                                  .smmy-        -oo+-                                                                                                                hMN         oMM-        `::`:-  -` .:--:`-.:-.: .:---:.            `+hdy:                                                          `+ss+.           "<<endl;                                                                       
          std::cout<<"          `/yyo-                                                                                                                  .odmy-        -os+-                                                                                                              hMN         oMM-                       ``                        `/hdy:                                                          `/ss+.             "<<endl;                                                                       
          std::cout<<"            `/yyo-                                                                                                                  .odmy-        -oo+.                                                                                                            hMN         oMM-                    .ydhhdh-                   `/hdy:                                                          `/ss+.               "<<endl;                                                               
          std::cout<<"              `+yyo-                                                                                                                  .sdmy-        :oo:                                                                                                           hMN         oMM-    `.-------------:mh`  `oN/----------------:+hdds:--------------------------------------------------------:/oss+.                 "<<endl;                                                                       
          std::cout<<"                ./yyo-                                                                                                                  .sdms-       -oo-                                                                                                         `hMN         oMM- ./sssssooooooooooosNy    +Myoooooooooooooosyddhysooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo+/-`                   "<<endl;                                                                       
          std::cout<<"                  `/yyo-                                                                                                                  -smds-     `os:                                                                                `..`                   `odhhhdo`    `sdddddhs/-``             :hdysdd/`            `/hdy:`                                                                                    "<<endl;                                                                       
          std::cout<<"                     .+yyo-                                                                                                                  -sdds-   `os:   :/+.`..-:``...`..  +:.-:`..`..``..`/`                                        -+:`- ..-.-/`---.--.   oN-`  -ms    hd.```+N/                   .--.`             :ydy:`                                                                                      "<<endl;                                                                       
          std::cout<<"                       .+yyo-                                                                                                                  -sdds- `os:   //:::-o-o/`s-/::   .::-:`o`:/-:o-/.+                                         -+.`+`+.//./`o`+:/.+   oN-   .my    dd`   /M/                                   :ydy/`                                                                                        "<<endl;                                                                       
          std::cout<<"                         .+yyo-                                        `...                                                                      -sdds:sy+`  .:-.:-:...`-:-..   .:-`:.- `:-`--- :-                                        `..``..`.. .``..`` `   `hNhsyds`   -smdsshNo                                  :ydy/`                                                                                          "<<endl;                                                                       
          std::cout<<"                          .+yyo-.`                                  .yhyyhh/                                                                     `-hNdyyyd+`                                                                                                   -yNNy:-`   -+ss/--sNMh-                  -+sso/`      :sdy/`                                                                                            "<<endl;                                                                       
          std::cout<<"                             ./syysssssssssssssssssssssssssssssssssssmh`  `+Nyssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssmd`  `/Nysssss+:.                                                                                         -yNNy-     .+ss/`    -yNNy/-..............+mo:-/hd-...:sdds:-.................................................`                                           "<<endl;                                                                      
